stages:
  - build
  - test
  - deploy
build:
  stage: build
  script:
  - echo "Compilando..."

test:
  stage: test
script:
  - echo "Ejecutando pruebas..."

deploy:
  stage: deploy
  script:
    - echo "Desplegando..."
   
  environment:
    name: production
   
